# file: generic-users/tasks/main.yml

- name: generic-users | Make sure all groups are present
  group:
    name: "{{ item.name }}"
    system: "{{ item.system | default(omit) }}"
    gid: "{{ item.gid | default(omit) }}"
    state: present
  no_log: true
  with_items: "{{ genericusers_groups }}"

- name: generic-users | Make sure the users are present
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | join(',') if item.groups is defined else omit }}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ item.pass | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: present
  no_log: true
  with_items: '{{ genericusers_users }}'

- name: generic-users | Install the ssh keys for the users
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1}}"
  no_log: true
  with_subelements:
    - "{{ genericusers_users }}"
    - ssh_keys

- name: generic-users | Make sure all removed users are not present
  user:
    name: "{{item.name}}"
    state: absent
    remove: yes
  no_log: true
  with_items: "{{ genericusers_users_removed }}"

- name: generic-users | Make sure all removed groups are not present
  group:
    name: "{{ item.name }}"
    state: absent
  no_log: true
  with_items: '{{ genericusers_groups_removed }}'
